services:
  e2e:
    container_name: e2e
    build:
      context: .
      dockerfile: ./docker/e2e/Dockerfile
    volumes:
      - ./app/e2e/:/e2e/
    restart: on-failure
    env_file:
      - ./app/e2e/.env.test
    depends_on:
      - webview
      - webapi

  webview:
    container_name: webview
    build:
      context: .
      dockerfile: ./docker/webview/Dockerfile
    volumes:
      - ./app/webview/src/:/webview/src/
    ports:
      - "${WEBVIEW_PORT}:${WEBVIEW_PORT}"
    restart: always
    env_file:
      - ./app/webview/.env.test
    depends_on:
      - webapi

  webapi:
    container_name: webapi
    build:
      context: .
      dockerfile: ./docker/webapi/Dockerfile
    volumes:
      - ./app/webapi/:/webapi/
    ports:
      - "${WEBAPI_PORT}:${WEBAPI_PORT}"
    restart: always
    env_file:
      - ./app/webapi/.env.test
    depends_on:
      - rdb


  rdb:
    container_name: rdb
    build:
      context: .
      dockerfile: ./docker/rdb/Dockerfile
    volumes:
      - type: bind
        source: ./app/rdb/postgresql/test
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${RDB_NAME}
      POSTGRES_USER: ${RDB_USER}
      POSTGRES_PASSWORD: ${RDB_PASSWORD}
    ports:
      - "127.0.0.1:${RDB_PORT}:${RDB_PORT}"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${RDB_USER} -d ${RDB_NAME}"]
      interval: 1s
      timeout: 3s
      retries: 30

  kvs:
    container_name: kvs
    build:
      context: .
      dockerfile: ./docker/kvs/Dockerfile
    volumes:
      - type: bind
        source: ./app/kvs/redis/test
        target: /data
    ports:
      - "127.0.0.1:${KVS_PORT}:${KVS_PORT}"
    restart: always

  vector:
    container_name: vector
    build:
      context: .
      dockerfile: ./docker/vector/Dockerfile
    volumes:
      - type: bind
        source: ./app/vector/qdrant/test
        target: /qdrant/storage
    ports:
      - "127.0.0.1:${VECTOR_PORT}:${VECTOR_PORT}"
    restart: always

  graph:
    container_name: graph
    build:
      context: .
      dockerfile: ./docker/graph/Dockerfile
    volumes:
      - type: bind
        source: ./app/graph/neo4j/test
        target: /data
    ports:
      - "127.0.0.1:${GRAPH_PORT}:${GRAPH_PORT}"
    restart: always